### ISSUE TITLE
Limit the width of table column when certain column is too long

### ISSUE THREAD

**Issue by ckangnz** [kkvh/vim-docker-tools#37]
I have really long docker Image name and it makes the table look ugly.
It would be really nice to have elipsis on all columns if they're too long like how COMMAND column does?

**Comment by kkvh** [comment]
This plugin will not further process the output from docker commands (the COMMAND column is truncated by docker itself). However, I have now added an option to format the output (#38), where you can achieve something close to that. For example, if you have a long container name, you can try:
```
let g:dockertools_container_format = 'table {{printf "%.10s" .Names}}'
```
That will limit the container name up to 10 characters. For the formatting options please refer to the [official Docker documentation](https://docs.docker.com/config/formatting/).
