### ISSUE TITLE
Plugin not working on Windows

### ISSUE THREAD

**Issue by sysnet-ai** [kkvh/vim-docker-tools#40]
Hi I'm a big fan of the project but I have been having some issues on windows:

Vim Version:
```
VIM - Vi IMproved 9.0 (2022 Jun 28, compiled Nov  5 2023 23:49:43)
MS-Windows 64-bit GUI version with OLE support
Included patches: 1-2092
Compiled by appveyor@APPVEYOR-VM     
```

Currently `:DockerToolsOpen` opens a panel with the following text:
```
# Press ? for help
"docker container ls" accepts no arguments.
See 'docker container ls --help'.

Usage:  docker container ls [OPTIONS]

List containers
```

The command `docker container ls -a` works correctly from any terminal and even from vim doing `:!docker container ls -a` so I'm unsure of what could be happening.

I tried to debug the plugin, but my understanding of vimscript is not the greatest and couldn't get any obvious leads.

Thanks again for the project and hope there's an easy fix for this one.

**Comment by kkvh** [comment]
Hi @sysnet-ai, thank you for your support to the project!

Unfortunately, I do not have a Windows PC to reproduce this issue, can you please perform the following steps and let me know what is the result?

1. Switch to branch `debug/docker-ls-format`
2. Run `:DockerToolsOpen`
3. Paste the debug message here, which starts with `docker-tools: `

**Comment by sysnet-ai** [comment]
Hi @kkvh - Thanks a lot for the swift response. This is what I'm seeing in the new branch:
![image](https://github.com/kkvh/vim-docker-tools/assets/16857363/006c38b9-8956-4d68-92a5-d9b5e75a00f1)

**Comment by kkvh** [comment]
Can you execute the same command in terminal? Also, what is the result of the following vim command?
```
:set shellslash?
```
Thank you.

**Comment by sysnet-ai** [comment]
Hi @kkvh - It ended up being the shellslash.

I had it set (for other plugins), if I unset it this works like a charm.

I don't know if there's anything to be done - I'll let you close it then. Thanks a lot.

**Comment by kkvh** [comment]
Hi @sysnet-ai thank you for letting me know that you have resolved the issue by having the `shellslash` option unset. Currently I prefer not to do anything with this option so I am going to close this issue for now.
